SkyBlock-Nerds/NerdBot

src/main/java/net/hypixel/nerdbot/bot/impl/NerdBot.java, src/main/java/net/hypixel/nerdbot/channel/ChannelGroup.java, src/main/java/net/hypixel/nerdbot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/database/Database.java, src/main/java/net/hypixel/nerdbot/database/GreenlitMessage.java
=> Clean up Aerh's variables

src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java
I don't know if this actually works. Someone please test.
=> Strip messages of mentions

src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java
=> 2nd attempt at private messages

src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/channel/ReactionChannel.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/java/net/hypixel/nerdbot/listener/ReactionChannelListener.java
Adds a new type of channel named a Reaction Channel
A Reaction Channel will automatically add new emojis in the order defined in the configuration file to all new messages in the specified channel
Each Reaction Channel is defined in the bot's configuration file as such:
```json
"reactionChannels": [
{
"name": "Test Reaction Channel",
"discordChannelId": "1234567890",
"emojiIds": [
"1234567890",
"1234567890"
]
},
{
"name": "Voting Channel",
"discordChannelId": "1234567890",
"emojiIds": [
"1234567890",
"1234567890"
]
}
]
```
=> Reaction Channels

src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java
Fixes the issue where not closing a `%%` causes errors
=> Fix ending non-escaped `%%` errors

src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java, src/main/java/net/hypixel/nerdbot/generator/ImageMerger.java, src/main/java/net/hypixel/nerdbot/generator/MinecraftHead.java, src/main/java/net/hypixel/nerdbot/generator/MinecraftImage.java, src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/java/net/hypixel/nerdbot/util/Util.java
- Fix issues with item gen commands "working" in threads
- Fix for `\n` at the end of a Item's Description
- Implements rendering for the unseen parts of the cube
- Fix for mod mail throwing errors (probably not needed)
=> Head Generation Fixes

src/main/java/net/hypixel/nerdbot/util/skyblock/MCColor.java
theoretically added %%RESET%% and &r to reset the color back to gray
=> Update MCColor.java for my yearly contribution

src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
Change info commands to much nicer EmbedBuilders
=> Embed info

src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
someone pls refactor thanks, too many "description" in this file
=> Change display name for textgen input

src/main/java/net/hypixel/nerdbot/generator/MinecraftHead.java
Changes the color of transparency used on the skin's hat texture in case it uses white or another color for transparency
Before...
After...
=> Adds check to see if the skin uses a different color for transparency

pom.xml, src/main/java/net/hypixel/nerdbot/api/database/Database.java, src/main/java/net/hypixel/nerdbot/api/database/model/reminder/Reminder.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/command/UserCommands.java
Adds new functionality to the bot to allow users to create reminders
Commands:
- /remind create time description
- /remind delete uuid
- /remind list
I am unsure on the formatting and whether it's what people want, but feedback/suggestions welcome. Mostly looking for ideas on how to send reminders to people whether it should be in the channel visible for everyone or through DM's.
=> Add support for reminders

src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This PR is made to give users visual feedback that the request was processed by the bot, and is being looked at.
=> Feedback to users DMing modmail.

src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This moves away from Caffeine caching for the suggestion cache, and uses a timer task to update the cache once an hour.
=> Fix suggestion cache permanently

src/main/java/net/hypixel/nerdbot/command/UserCommands.java
Put the filtering by alpha into the filters section, rather than in every embed.
=> Cleanup Suggestions

src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java, src/main/java/net/hypixel/nerdbot/feature/CurateFeature.java, src/main/java/net/hypixel/nerdbot/feature/GreenlitUpdateFeature.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/listener/SuggestionListener.java, src/main/java/net/hypixel/nerdbot/util/Util.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This fixes deleted suggestions showing up in /suggestions. It also fixes all remaining null array stream issues.
=> Fix deleted suggestions

.github/workflows/generate-config.yml, pom.xml, src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/EmojiConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/ModMailConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/TagConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/resources/example-config.json
This branch implements a new GitHub Action that will build the project and run the ConfigGenerator class, which will generate a new example-config.json file and push it to the branch. 
We will no longer have to manually update the example config file.
See this commit for an example:
https://github.com/TheMGRF/NerdBot/commit/171c4245a138d0ff9ea0f57bd8c021ab3f9753f4
=> Automatically generate an example-config.json file when changes to the config classes are detected

.github/workflows/main.yml
Update the GitHub Workflow to Java 18
=> Update to Java 18

src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java
- Made error messages accurate to what the user is supposed to do.
=> Fix not escaping % for formatted strings

src/main/resources/minecraft_assets/spritesheets/atlas_coordinates.json
Fixes Leather Armor not lining up
=> Fixes leather armor overlay

src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java
- Fix NPE for unlinked users
- Notify user if they're unlinked as often as updating the first post
- On unarchive
- On new
- On first post change
=> Fix NPE for unlinked users

src/main/java/net/hypixel/nerdbot/command/MyCommands.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java
- Make `/link` global for DM access
- Add hyperlink to `/link` from DMs for unlinked users
=> Update /link command

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorBuilder.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java, src/main/java/net/hypixel/nerdbot/generator/MinecraftImage.java, src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java
- Adds the `centered` (`True/False`) parameter to `/gen text` which allows text to be displayed in the middle automatically (`False` by default).
- Adds acknowledgement of `/gen text` existing with it's 1 parameter.
- Internal Optimisations for Initial Image Width.
=> Text Centeralisation

src/main/java/net/hypixel/nerdbot/generator/GeneratorBuilder.java
Fixes an under estimation for initial image width
=> Fix under estimation for initial image width

src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
A small QOL feature for if reminders are public or not.
=> Public Reminders

pom.xml, src/main/java/net/hypixel/nerdbot/NerdBotApp.java, src/main/java/net/hypixel/nerdbot/util/JsonUtil.java, src/main/java/net/hypixel/nerdbot/util/Tuple.java, src/main/java/net/hypixel/nerdbot/util/URLWatcher.java
Adds a new class called URLWatcher that can be used to detect changes in a JSON response over time.
Some example use cases:
- Changes in player data
- New status page updates/modifications
This is purely the implementation to detect changes in responses and includes none of the above.
Example usage:
```java
URLWatcher urlWatcher = new URLWatcher("https://api.hypixel.net/counts", Map.of("API-Key", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"));
urlWatcher.startWatching(5, TimeUnit.SECONDS, (oldContent, newContent, changedValues) -> {
log.info("Changed Values:");
changedValues.forEach(tuple -> {
log.info(tuple.value1() + ": " + tuple.value2() + " -> " + tuple.value3());
});
});
```
Output from above example:
```
[2023-09-22 20:14:52.746] [INFO] [Timer-6] [NerdBotApp] Changed Values:
[2023-09-22 …
```
=> Add class to detect changes in a JSON response over time

src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/command/RoleCommands.java, src/main/java/net/hypixel/nerdbot/util/ClassUtil.java, src/main/java/net/hypixel/nerdbot/util/LoggingUtil.java
Adds the `/loglevel <level>` command which is locked from normal users by default. It allows members with permission to set the logging level used by any class logger
=> Add /loglevel command

src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java
- Fixes an RasterOverflowError caused when the final line doesn't wrap it's text
=> Fixes Overflow Error

src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/bot/config/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/listener/PinListener.java, src/main/resources/example-config.json
Automatically pins first messages in forum threads.
Additionally, it fixes a bug when making a regular thread giving an error.
=> Autopinning

src/main/java/net/hypixel/nerdbot/listener/PinListener.java
(This is just to look nice, we only want to see those types of messages from real people!)
=> Deletes automated pin messages from any bot.

src/main/java/net/hypixel/nerdbot/api/database/model/greenlit/GreenlitMessage.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/command/InfoCommands.java, src/main/java/net/hypixel/nerdbot/repository/GreenlitMessageRepository.java
Changes the /info greenlit command to use components and a fancy embed
=> Reformat the /info greenlit command

src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
A message sent in DMs whenever you make a reminder to when you made a reminder and its UUID.
=> Small reminder qol

src/main/java/net/hypixel/nerdbot/NerdBotApp.java, src/main/java/net/hypixel/nerdbot/util/gson/adapter/DateDeserializer.java, src/main/java/net/hypixel/nerdbot/util/gson/adapter/UUIDTypeAdapter.java
Fixes the Date objects in Mongo documents expecting a string date when it's reading a Date object
=> Fix Date objects in documents causing errors

src/main/java/net/hypixel/nerdbot/NerdBotApp.java
Turns out adding this broke more stuff /shrug
=> Remove DateDeserializer

src/main/java/net/hypixel/nerdbot/command/AdminCommands.java
For whatever reason it was working fine locally but not on the main bot, but I fixed it
=> Fix /lock Command Message

src/main/java/net/hypixel/nerdbot/NerdBotApp.java, src/main/java/net/hypixel/nerdbot/api/urlwatcher/URLWatcher.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/urlwatcher/FireSaleDataHandler.java, src/main/java/net/hypixel/nerdbot/util/JsonUtil.java, src/main/java/net/hypixel/nerdbot/util/Tuple.java
Changes stuff in the Fire Sale URLWatcher to only display the changed items
=> Fix Fire Sale Watcher

src/main/java/net/hypixel/nerdbot/api/database/model/reminder/Reminder.java, src/main/java/net/hypixel/nerdbot/api/database/model/user/BirthdayData.java, src/main/java/net/hypixel/nerdbot/api/database/model/user/DiscordUser.java, src/main/java/net/hypixel/nerdbot/api/repository/Repository.java, src/main/java/net/hypixel/nerdbot/api/urlwatcher/handler/SkyBlockUpdateDataHandler.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/channel/ChannelManager.java, src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/command/MyCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/java/net/hypixel/nerdbot/feature/UserGrabberFeature.java, src/main/java/net/hypixel/nerdbot/repository/DiscordUserRepository.java, src/main/java/net/hypixel/nerdbot/repository/GreenlitMessageRepository.java, src/main/java/net/hypixel/nerdbot/urlwatcher/FireSaleDataHandler.java
Adds the ability to set, check and remove a birthday date from your profile.
Once a birthday date is reached, a message will be sent in the #general channel. Then it will schedule a new timer for the same date a year after. If a birthday date is changed then the existing timer will be cancelled and a new timer will be created.
=> Birthday Messages

src/main/java/net/hypixel/nerdbot/command/AdminCommands.java
=> Add Reviewed forum tag when /lock is ran on a suggestion thread

src/main/java/net/hypixel/nerdbot/util/skyblock/Stat.java
=> add taming wisdom

src/main/java/net/hypixel/nerdbot/command/GoogleCommands.java
Exports all threads in a forum channel into a CSV file, separated by the ; character
=> Create /export threads Command

src/main/java/net/hypixel/nerdbot/api/database/model/user/UserLanguage.java, src/main/resources/languages/german.json
Thanks to Apfelbastian for translating!
=> :flag_de: Added translation support for German

src/main/java/net/hypixel/nerdbot/api/database/model/user/stats/LastActivity.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java
- Remove the activity migration methods/fields
- Fix alpha/project text channel activity tracking
=> Post Activity Migrate

src/main/java/net/hypixel/nerdbot/api/curator/Curator.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/curator/ForumChannelCurator.java, src/main/java/net/hypixel/nerdbot/curator/ForumGreenlitChannelCurator.java, src/main/java/net/hypixel/nerdbot/feature/CurateFeature.java, src/main/java/net/hypixel/nerdbot/util/TimeUtil.java
Adds context to the Curator class of the current index, total amount of objects to curate, the current object, and whether it's completed
=> Curator Context

src/main/java/net/hypixel/nerdbot/cache/suggestion/Suggestion.java, src/main/java/net/hypixel/nerdbot/listener/SuggestionListener.java, src/main/java/net/hypixel/nerdbot/util/Util.java
Updates the configured project channel IDs when ChannelNameUpdateEvent is now triggered
Also moves applicable project channel names into an array
=> Update Configured Project Channel IDs

pom.xml, src/main/java/net/hypixel/nerdbot/bot/config/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/command/InfoCommands.java, src/main/java/net/hypixel/nerdbot/listener/ReactionChannelListener.java
Adds emojis sent in a message in a configured poll channel as reactions for other people to vote with
=> Poll Channel Reactions

src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
Allows users to use a raw timestamp as a time when creating a reminder
=> Allow raw timestamps in /remind create

src/main/java/net/hypixel/nerdbot/command/InfoCommands.java, src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/resources/languages/english.json
Adds more permission checks when members are viewing suggestions
=> Suggestion Viewer Permission Checks

CONTRIBUTING.md, Dockerfile, README.md
Updates any references to the old repository location to the new organisation name
=> Change Repository References

src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/resources/example-config.json
Adds fake data to the `example-config.json` file to better represent what data goes in those areas
=> Example Config Enhancements

src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java
=> Add Suggestion Creation Date to Suggestion Search

src/main/java/net/hypixel/nerdbot/command/ExportCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/java/net/hypixel/nerdbot/curator/ForumChannelCurator.java, src/main/java/net/hypixel/nerdbot/curator/ForumGreenlitChannelCurator.java, src/main/java/net/hypixel/nerdbot/util/Util.java, src/main/java/net/hypixel/nerdbot/util/csv/CSVData.java
Creates a new command called `/export member-activity` that outputs a CSV file with member information and activity. This file can be imported into a spreadsheet editor of choice
This PR also creates a new CSVData class and moves all existing CSV-related functionality into that class
=> Create Member Activity Export Command

src/main/java/net/hypixel/nerdbot/bot/config/channel/AlphaProjectConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/channel/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/java/net/hypixel/nerdbot/bot/config/objects/CustomForumTag.java, src/main/java/net/hypixel/nerdbot/command/ChannelCommands.java, src/main/java/net/hypixel/nerdbot/listener/SuggestionListener.java, src/main/resources/example-config.json, src/main/resources/languages/dutch.json, src/main/resources/languages/english.json, src/main/resources/languages/german.json, src/main/resources/languages/pirate_speak.json
Add support for custom user-based tags in the `/lock` command
=> Custom Tag Support

src/main/java/net/hypixel/nerdbot/util/skyblock/Gemstone.java
=> Fix name of peridot gemstone

src/main/java/net/hypixel/nerdbot/api/database/model/user/DiscordUser.java, src/main/java/net/hypixel/nerdbot/bot/config/channel/ChannelConfig.java
Changes the birthday notification channel from being a hardcoded value of "general" to being configurable in the ChannelConfig class
=> Configurable Birthday Notification Channel

src/main/java/net/hypixel/nerdbot/bot/config/channel/AlphaProjectConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/channel/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/java/net/hypixel/nerdbot/bot/config/suggestion/SuggestionConfig.java, src/main/java/net/hypixel/nerdbot/listener/PinListener.java, src/main/resources/example-config.json
AlphaProjectConfig.java, SuggestionConfig.java, ConfigGenerator.java
Removal of the autopin setting. Never necessary in the first place.
ChannelConfig.java, ConfigGenerator.java
Addition of the global autopin setting along with a blacklist of channels if wanted.
PinListener.java
Practically a reversion to the previous working case except with an added blacklist forum channel list.
=> Autopinning v2

src/main/java/net/hypixel/nerdbot/api/database/model/user/DiscordUser.java, src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/command/UserCommands.java, src/main/resources/languages/english.json
I still have to add the config setting for the default autohide value which is currently in code (set to ~~true~~ false).
Also couldn't find any unit tests?
First Java code contribution so if there are any mistakes having to do with conventions etc please say so.
=> Added Auto Hide gen commands setting

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/command/UserCommands.java, src/main/java/net/hypixel/nerdbot/generator/data/PowerStrength.java, src/main/java/net/hypixel/nerdbot/generator/data/Stat.java, src/main/resources/data/powerStrengths.json, src/main/resources/data/stats.json
=> Feat v2 gen powerstone (attempt #2)

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/generator/impl/tooltip/MinecraftTooltipGenerator.java, src/main/resources/data/stats.json, src/main/resources/languages/english.json
[standardized hidden == null check](https://github.com/SkyBlock-Nerds/NerdBot/commit/4121a821f0d1e231520df9bd1ef5653b2b271f99) and [gave the searchItem method a line per param](https://github.com/SkyBlock-Nerds/NerdBot/commit/7da1208ee5588e7019e17daa92e6d1293b57dc4c)
=> cleaned up some code

src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java
Mention the configured Moderator role ID when a new verification request is submitted by a user
=> Add Verification Request Pings

src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java
Apparently appendDescription and setDescription are basically the same thing so I fixed it
=> Fix Verification Request Pings

src/main/java/net/hypixel/nerdbot/util/skyblock/Icon.java
Adds `⛃` as an icon under the RAFFLE entry
=> Add RAFFLE Icon

src/main/java/net/hypixel/nerdbot/api/database/model/reminder/Reminder.java, src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
This feature is being removed as, in a majority of cases, it was not being used for its original intended purpose. All reminders will be sent via DM now regardless of the channel the command is used in
=> Remove option to send public reminders

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java
This is more of a hacky, temporary (hopefully) fix for the `/gen help symbols` command constantly throwing errors. Once we migrate to a command framework that doesn't constantly throw errors with Postgres connections then we can revisit this
=> Fix /gen help symbols

src/main/java/net/hypixel/nerdbot/util/skyblock/Flavor.java, src/main/java/net/hypixel/nerdbot/util/skyblock/Stat.java
https://discord.com/channels/610249706106257448/1351615807377113169/1351615807377113169
=> Added New Fishing flavors and stat to parser

src/main/java/net/hypixel/nerdbot/util/skyblock/Gemstone.java
(used to be sea creature chance but now is fishing speed)
=> Fixed Aquamarine Gemstone icon

src/main/java/net/hypixel/nerdbot/generator/parser/text/StatParser.java
=> Reset formatting after parsed stats (redo)

.editorconfig, src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/resources/example-config.json, src/main/resources/languages/dutch.json, src/main/resources/languages/english.json, src/main/resources/languages/german.json, src/main/resources/languages/pirate_speak.json
Was changed in /generator but not here, since it was approved by Aerh in /generator, I assume we want it to be 4 everywhere.
=> Changed json indentation to 4 (master)

src/main/java/net/hypixel/nerdbot/bot/config/generator/ConfigGenerator.java, src/main/resources/example-config.json, src/main/resources/languages/dutch.json, src/main/resources/languages/english.json, src/main/resources/languages/german.json, src/main/resources/languages/pirate_speak.json, src/main/resources/minecraft/json/atlas_coordinates.json
Changed json files which weren't 4 indented to 4 indent.
(Just did all the files even if they exist on /master because the languages have some new lines and I don't wanna go and check which ones are new or not and only indent those)
(Also now with merge conflicts you can choose the /generator file instead of having to choose each line painstakingly.)
=> Standardized json indentation (generator)

src/main/java/net/hypixel/nerdbot/command/ModMailCommands.java, src/main/java/net/hypixel/nerdbot/feature/UserNominationFeature.java
=> Attach ModMail Thread to Inactive User Message

.github/workflows/build-test.yml
Also now triggers on push but wont trigger on push and pr
=> Better workflow for people with write

src/main/java/net/hypixel/nerdbot/api/database/model/user/stats/LastActivity.java, src/main/java/net/hypixel/nerdbot/api/database/model/user/stats/NominationInfo.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/bot/config/channel/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/objects/RoleRestrictedChannelGroup.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java, src/main/java/net/hypixel/nerdbot/feature/UserNominationFeature.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/listener/RoleRestrictedChannelListener.java, src/main/resources/example-config.json, src/main/resources/languages/english.json
Adds new configuration options to create restricted channel groups based on what roles can access it, and records these metrics in user data separate to the global user activity data.
=> Restricted Channel Activity Checks

src/main/resources/data/stats.json
Actually noticed this because of the ai review, I was really not on point when making those pr's, multiple formatting mistakes is kinda sad.
and even more now not checking the branch when making the pr...
=> Fixed capitalization
