src/main/java/net/hypixel/nerdbot/curator/Curator.java
pretty self explanatory, doesn't actually remove the reaction just doesn't count it. would be more efficient by substracting it from where the the reactions are tracked but sadly java lambdas suck. kt port when
=> make own votes not count to greenlight

src/main/java/net/hypixel/nerdbot/command/GetNamesCommand.java
Makes changes to allow members to add unique characters not apart of their MC Username for extra **flair** in SBN.
Requires the name to be split by a non-alphabetic or numeric character.
**Tested Cases for Discord Usernames**
```
R4PlD -> R4PlD
R4PlD    -> R4PlD
1234567890123456 -> 1234567890123456
1234567890123456🍇 -> 1234567890123456
R4PlD (mod dev) -> "R4PlD
R4PlD(mod dev) -> "R4PlD
```
=> Better regex scanning when running /getnames command

src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java, src/main/java/net/hypixel/nerdbot/util/skyblock/Stat.java
Users can use `%%&<StatName>%%` to display the stat's icon at the required location.
| i.e. `%%&speed%%` turns into `%%white%%✦`
=> Allows using & before stats to only display the icon with its color

src/main/java/net/hypixel/nerdbot/command/InfoGenCommand.java, src/main/java/net/hypixel/nerdbot/command/ItemGenCommand.java, src/main/java/net/hypixel/nerdbot/generator/MinecraftImage.java
This replaces the transparent parameter in /itemgen with alpha and allows the user to enter a value between 0 and 255, 0 looking like an in-game chat message, 255 being the item lore black/default background.
=> Change itemgen to take an alpha value directly for the background layer

src/main/java/net/hypixel/nerdbot/generator/MinecraftImage.java
Yes this is literally just changing a 5 to a 0.
Before:
After:
=> Fixed bold characters looking strange

src/main/java/net/hypixel/nerdbot/api/database/greenlit/GreenlitMessage.java, src/main/java/net/hypixel/nerdbot/api/database/user/LastActivity.java, src/main/java/net/hypixel/nerdbot/api/feature/BotFeature.java, src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/EmojiConfig.java, src/main/java/net/hypixel/nerdbot/command/InfoCommands.java, src/main/java/net/hypixel/nerdbot/curator/ForumChannelCurator.java, src/main/java/net/hypixel/nerdbot/feature/CurateFeature.java, src/main/java/net/hypixel/nerdbot/feature/GreenlitUpdateFeature.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/resources/example-config.json
This adds code to separate Suggestion and Alpha activity for users in the database. It also adds an alpha tag for GreenlitMessage's in the database.
The following config fields in the build process and server storage need to be updated:
> suggestionForumId : suggestionForumIds
The following database fields in LastActivity need to be migrated and associated class files updated:
> lastGlobalActivity : globalMostRecent
> lastVoiceChannelJoinDate : globalVoiceJoinDate
> lastItemGenUsage : itemGenUsage
> lastSuggestionDate : suggestionCreationDate
> lastAlphaActivity : alphaMostRecent
> lastAlphaSuggestionDate : alphaSuggestionCreationDate
=> Separate Suggestion and Alpha User Activity

src/main/java/net/hypixel/nerdbot/api/database/greenlit/GreenlitMessage.java, src/main/java/net/hypixel/nerdbot/curator/ForumChannelCurator.java, src/main/java/net/hypixel/nerdbot/feature/CurateFeature.java, src/main/java/net/hypixel/nerdbot/feature/GreenlitUpdateFeature.java
This implements a change to Greenlit Suggestion curating that saves the user IDs of anyone who positively votes (agrees) with a suggestion, when it is curated and Greenlit. It also updates the greenlit suggestion embed with this information, dubbed "Pre-Greenlit Voters"
=> Track users who positively greenlit a suggestion

src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java, src/main/java/net/hypixel/nerdbot/generator/ColoredString.java, src/main/java/net/hypixel/nerdbot/generator/StatColorParser.java, src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java, src/main/java/net/hypixel/nerdbot/util/skyblock/MCColor.java, src/main/java/net/hypixel/nerdbot/util/skyblock/Stat.java
- Adds a new command `/itemgenparse` which will convert the display tag in the NBT of an item into a format which is displayable with the bot.
- This should only accept a full JSON object with both a `Name` string and `Lore` array.
- Adds new stats `ABILITY` which acts similar to `ITEM_STAT_GREEN`
- `%%ABILITY:Instant Transmission:RIGHT CLICK%%` -> `%%GOLD%%Ability: Instant Transmission%%YELLOW%%%%BOLD%%RIGHT CLICK`
-  Adds new stat `COOLDOWN` which puts the text after it in green
- Fix for the items description from being chopped off
- Fix for the `itemgen` command displaying a message in channels it isn't supposed to
- Fix for being able to set the line length to 0
- Fix typos in comments and added missing function comments
=> New Stats and `/itemgenparse`

src/main/java/net/hypixel/nerdbot/NerdBotApp.java, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/command/UserCommands.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/listener/SuggestionListener.java, src/main/java/net/hypixel/nerdbot/util/discord/MessageCache.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This is a followup to https://github.com/TheMGRF/NerdBot/pull/86 that caches all suggestion threads on startup. It's garbage collector safe with a 1 hour expiry time and auto-renew once an hour.
There's also a 2nd attempt at fixing reading archived public threads from suggestion forums.
=> Cache suggestion threads on startup

src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/bot/config/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/channel/ChannelManager.java, src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java, src/main/java/net/hypixel/nerdbot/feature/CurateFeature.java, src/main/java/net/hypixel/nerdbot/feature/GreenlitUpdateFeature.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/listener/ReactionChannelListener.java, src/main/java/net/hypixel/nerdbot/listener/SuggestionListener.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This PR moves channel-related config stuff to its own class called ChannelConfig
It also implements a new feature to blacklist channels from incrementing a user's message count
=> Add support for blacklisting channels from activity tracking

src/main/java/net/hypixel/nerdbot/bot/config/BotConfig.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java
- This adds a minimum number of seconds someone must be in the same voice channel for it to count as activity.
- Moves the time saved from joined to left, to account for long periods in voice channels.
- Voice channel moving resets the timer.
=> Add voice activity threshold

src/main/java/net/hypixel/nerdbot/command/UserCommands.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This is because over time, the suggestions get purged from the users cache, so grabbing them here lets users know what threads they are actually looking at.
=> Adding Titles into the buildSuggestionsEmbed.

src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/bot/config/ChannelConfig.java, src/main/java/net/hypixel/nerdbot/channel/ChannelManager.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/command/MyCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java, src/main/java/net/hypixel/nerdbot/listener/VerificationListener.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
This branches off from /link and builds a /verify command.
- Setup a verification log channel in config
- The `/verify` command works similarly to `/link` but sends the request to staff for review
- On accept
- Saves the users mojang profile
- If limbo and new member role IDs are setup, migrate them from Limbo to New Member
- On deny
- Adds a button to kick the member
- Requires clicking it 3 times
- On the 3rd click it will send a message asking for confirmation one last time (just to be sure)
- Clicking the Kick Now button will finally kick the user and log to the verification channel
=> Add member verification

src/main/java/net/hypixel/nerdbot/command/AdminCommands.java
Requested by Flare
Adds a `/flared` slash command which only works within threads in forum channels that have a "flared" tag. The command will not work in other forum channels that don't have said tag.
It applies this tag and locks the suggestion, sending a message to everybody saying the suggestion was "flared" and locked
=> Add /flared slash command

src/main/java/net/hypixel/nerdbot/api/database/model/user/stats/LastActivity.java, src/main/java/net/hypixel/nerdbot/bot/config/ModMailConfig.java, src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorBuilder.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/resources/example-config.json
- Adds rolling timer (defaults to 60 seconds) before it pings the mod mail role again.
- Adds a config option to change where the mod mail role ping is located.
- Options are ABOVE, INLINE and BELOW (default)
- Removes head warning message when sending full URL
- Now uses a pattern matcher to support SSL URLs just in case.
- Moved mod mail role id out of class variables and into execution code so they can be changed using config editor.
This is the complete version of https://github.com/TheMGRF/NerdBot/pull/122
=> Less annoying modmail

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java
Fix an issue where Minecraft heads would not be displayed when using the `include_item` attribute for `/gen parse`
=> Displaying heads on `gen parse`

src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
Turns out you also have to flip the boolean when creating the new Reminder object, but this fixes it
=> Fix Reminder Visibility

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java
This is the only part of the bot that doesn't have a help command to preview all of the options, so here goes nothing
=> Add a help command to show all available colors

src/main/java/net/hypixel/nerdbot/generator/IconParser.java, src/main/java/net/hypixel/nerdbot/generator/StringColorParser.java, src/main/java/net/hypixel/nerdbot/util/skyblock/Icon.java
Added a repeating modifier to some icons. Specifying an amount after the icon name will repeat it that many items. Icons will be repeated ``max(1, amount)`` times. 
Examples:
``%%STAR%%`` -> ✪
``%%STAR:5%%`` -> ✪✪✪✪✪
``%%STAR:-1%%`` -> ✪ (invalid number) 
``%%STAR:0%%`` -> ✪ (invalid number) 
``%%STAR:test%%`` -> ✪ (not a number)
=> Added a modifier to repeat icons

src/main/java/net/hypixel/nerdbot/generator/GeneratorStrings.java
When performing the ``/gen help full`` command, it currently shows ``/GENs help recipe`` as a valid command.
This PR fixes the formatter string and now shows the correct command ``/gen help recipe``.
=> Fix Formatter string

src/main/java/net/hypixel/nerdbot/util/skyblock/Stat.java
Adds Rift Damage and Mana Regen to the list of stats.
Rift Damage uses the normal Damage Icon, so that's fine. The default text for Mana Regen looks close enough, that I didn't add it to the font file.
=> Add Rift Damage and Mana Regen as stats

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java, src/main/java/net/hypixel/nerdbot/generator/GeneratorBuilder.java, src/main/java/net/hypixel/nerdbot/generator/MinecraftImage.java
- Adds a black background color to all `/gen text` commands.
- This can be turned off by setting the alpha to 0
- Fixes underestimation again.
=> Text Gen Background Color

src/main/java/net/hypixel/nerdbot/bot/config/RoleConfig.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/command/InfoCommands.java, src/main/java/net/hypixel/nerdbot/command/MyCommands.java, src/main/java/net/hypixel/nerdbot/listener/MetricsListener.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/java/net/hypixel/nerdbot/role/PingableRole.java, src/main/java/net/hypixel/nerdbot/role/RoleManager.java, src/main/java/net/hypixel/nerdbot/util/Util.java, src/main/resources/example-config.json
Adds two new commands and configuration functionality for what we call pingable roles. These are roles that'll primarily be used for things like announcements of new Fire Sales, updates, etc etc.
Commands are:
- /roles
- /role <name>
The /role <name> command can only assign pingable roles specified in the new configuration section `pingableRoles` and /roles only lists these too
=> Pingable Roles

src/main/java/net/hypixel/nerdbot/channel/ChannelManager.java, src/main/java/net/hypixel/nerdbot/command/ModMailCommands.java, src/main/java/net/hypixel/nerdbot/listener/ModMailListener.java, src/main/java/net/hypixel/nerdbot/util/Util.java
Adds a new `/modmail` command with a few sub-commands:
- `/modmail find` finds the specified user's Mod Mail thread in the configured Mod Mail channel
- `/modmail new` forcefully creates a new Mod Mail thread in the channel. It does not send a message to the user when the thread is created.
Someone in the future should pull out all the Mod Mail functionality into its own class so we're not duplicating code
=> Add /modmail Command

pom.xml, src/main/java/net/hypixel/nerdbot/bot/NerdBot.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/util/discord/ComponentDatabaseConnection.java, src/main/java/net/hypixel/nerdbot/util/discord/SuggestionCache.java
Adds support for components using a SQL database. (yuck)
If you do not provide any details the bot will still run, only components will not be supported (which is not recommended)
The following properties are used:
- `db.postgres.host` (default `localhost`)
- `db.postgres.port` (default `5432`)
- `db.postgres.user` (default `postgres`)
- `db.postgres.password` (default `password`)
- `db.postgres.database` (default `postgres`)
I also changed the `mongodb.uri` property to be in line with this change, so it is now `db.mongodb.uri`
=> Component Support

src/main/java/net/hypixel/nerdbot/command/ReminderCommands.java
This change is specifically for if a reminder is public to addon a message linking to where it will be sent too later.
Discussion seemed to lean towards the 2 newlines + "In channel:" however this is still up for debate as I only got 3 responses to this inquiry.
=> Reminder QOL 2 Finale.

src/main/java/net/hypixel/nerdbot/bot/config/SuggestionConfig.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/resources/example-config.json
Enforces a minimum required age of a suggestion before it can be sent for a review request. The default is 7 days.
=> Enforce suggestion age

src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/resources/languages/english.json
When manually curating messages, the user was never given feedback when any suggestions were greenlit. 
Fixed translation to include the words "ms" after the time, and also include the arguments for the MS timings as well.
=> Manual Curation Feedback Fixes.

src/main/java/net/hypixel/nerdbot/api/curator/Curator.java, src/main/java/net/hypixel/nerdbot/cache/suggestion/Suggestion.java, src/main/java/net/hypixel/nerdbot/command/AdminCommands.java, src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java, src/main/java/net/hypixel/nerdbot/curator/ForumChannelCurator.java, src/main/java/net/hypixel/nerdbot/util/Util.java
- Running /lock will run the greenlit process
- The greenlit curator will ignore the reviewed tag
This will allow suggestions that reach greenlit threshold but get locked to become greenlit
=> Greenlit support for /lock

src/main/java/net/hypixel/nerdbot/cache/suggestion/Suggestion.java, src/main/java/net/hypixel/nerdbot/command/ProfileCommands.java, src/main/java/net/hypixel/nerdbot/command/SuggestionCommands.java
Adds a permission check to suggestion viewing and filtering so Members or New Members cannot see other rank-specific suggestions, etc.
=> Add Suggestion#canSee

src/main/java/net/hypixel/nerdbot/api/language/TranslationManager.java
Fixes an issue with translations if the given key did not exist in the user's language, it would complain about it not existing even if it did in the DEFAULT_LANGUAGE
Now we're also checking the DEFAULT_LANGUAGE for the key and displaying that instead, if it exists
If it still doesn't exist at that point it will display the error it did before
=> Translation Fix

src/main/java/net/hypixel/nerdbot/util/skyblock/Icon.java
Adds `✆` as an icon to the bot so it can be used in the item generators
=> Add Abiphone Call Icon

src/main/java/net/hypixel/nerdbot/command/GeneratorCommands.java
Add support for generating items inside threads in item gen channels. 
If the user uses the item gen command outside of a item gen thread, it'll still give the "This can only be used in the item generating channel." message
=> Make gen commands usable in threads

src/main/java/net/hypixel/nerdbot/bot/config/channel/AlphaProjectConfig.java, src/main/java/net/hypixel/nerdbot/listener/ActivityListener.java, src/main/java/net/hypixel/nerdbot/util/Util.java
In some cases the methods being used to determine the ChannelType of a channel were not correclty identifying the channel's type.
This _should_ be fixed now.
=> Fix ChannelType not identifying correctly

src/main/java/net/hypixel/nerdbot/bot/config/objects/ReactionChannel.java, src/main/java/net/hypixel/nerdbot/listener/ReactionChannelListener.java
Self explanatory
Uses a new boolean called `thread` in the configuration object for a reaction channel
=> Support threads in Reaction Channels

src/main/java/net/hypixel/nerdbot/generator/impl/tooltip/MinecraftTooltipGenerator.java
It is currently parsing to `gen2 item ...` but should be `gen2 item full ...`
with the `...` being the fields
=> Updated MinecraftTooltipGenerator.buildSlashCommand to fix a typo

Dockerfile
ENV vars can't be overriden but ARG vars can. Aka right now if you would pass any of the ENV vars in docker build cmd it wouldn't actually do anything with them.
Also do we really need the JAR_FILE_NAME variable because I don't understand why that would ever change. If you still want to have it in a var I could change it back to ENV and edit the contributing.md to not include it.
=> Changed ENV vars into ARG vars (in dockerfile)

src/main/java/net/hypixel/nerdbot/generator/text/wrapper/TextWrapper.java
See issue #355
The %%thing%% will still apply their formatting behind them but I assume that is intended?
Also, I don't know if we care but we do have some duplicate log messages that could originate from different locations. No clue if this is bad practise or not.
=> Fixed preserve formatting bug

src/main/java/net/hypixel/nerdbot/generator/parser/text/IconParser.java, src/main/java/net/hypixel/nerdbot/generator/parser/text/StatParser.java
Don't know if you agree with how it's done but it's already been done like this for the gemstone parser so I don't see an issue with it. Also this is by far the easiest way because otherwise there would be some insane keeping track of stuff be required in the 'TextWrapper.WrapString()' function and that would just be complicating an already complicated method even more.
=> Reset formatting after parsed stats

CONTRIBUTING.md, Dockerfile
- Made the docker file not rely on the git repo 
- No more build args
- Also means that you don't have to care about versioning of your jar
- Switched from [OpenJDK](https://hub.docker.com/_/openjdk) to [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)
- OpenJDK is depracated
- ET is more lightweight
- Cut down the final image size from 1.9gb to 534mb (aka a 71.8% file size decrease)
- Mainly done by:
- Not including unnecessary files from the root
- More lightweight runner image
- [Exec form](https://docs.docker.com/reference/dockerfile/#shell-and-exec-form) in entrypoint
=> Docker File Redo
